language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.5.5
  - DJANGO=1.6.8
  - DJANGO=1.7.1
before_install:
  - sudo apt-get install libjpeg-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
install:
  - pip install .
  - pip install -q Django==$DJANGO
  - pip install coveralls
script:
  coverage run --source=stdimage runtests.py
after_success:
  coveralls
